### ISSUE TITLE
.NET Framework v4.7 requires Creators Update. The thing is that…

### ISSUE THREAD

**Issue by TapeoDeGalop** [sonicretro/mania-mod-loader#1]
…my machine keeps failing to download Creators Update. Having been trying for months? Yeah that was a hassle and tiresome. The last solution MS provided (clean OS install) didn’t do jacksquat either.
![screenshot_20170903230659](https://user-images.githubusercontent.com/31606708/30010726-d5758c72-90ff-11e7-9845-ccfe174c42f9.png)
Mind toning down the target platform in Visual Studio and recompile the whole thing in a way that guarantees compatibility even with Win10 non-Creators Update?

**Comment by MainMemory** [comment]
Sure, which version do you need?

**Comment by MainMemory** [comment]
Have you tried [the installer](https://www.microsoft.com/en-us/download/details.aspx?id=55170) for .NET 4.7?

**Comment by sh1nakuma** [comment]
Hi. Same here, I ran offline/web installer. It gives me the following "Blocking Issues: The .NET Framework 4.7 is not supported on this operating system."
.NET 4.6.1 is my version.
I can run other mod managers for Sonic Adventure DX, Sonic Adventure 2, Sonic Lost World, and Sonic Generations.

**Comment by MainMemory** [comment]
Thank you for responding. I have updated the release to use .NET 4.6.1.
