### ISSUE TITLE
Plus/1.04 port?

### ISSUE THREAD

**Issue by soup587** [sonicretro/mania-mod-loader#16]
Is it ok to use this thread as a sort of "progress meter" on the port? I'm excited for the port and would like to know how long it is until the mod loader is ported.

**Comment by MainMemory** [comment]
You mean 1.05. I haven't started looking into it yet, and I don't think I will until tomorrow. Hopefully, once I do get started, it shouldn't take too long to finish, barring possibly some of the cheat codes.

**Comment by soup587** [comment]
Ok. The cheat codes are what I'm interested in, heh.
