### ISSUE TITLE
I don't know how to use this

### ISSUE THREAD

**Issue by tmvkrpxl0** [sonicretro/mania-mod-loader#19]
sorry to ask kind of like this, but i want to ask "is this thing requires build? if it is, how? how can i use this for installing mod?"
sorry, but i'm noob at this
how can i use it to install mod?
again, i'm really sorry

**Comment by tmvkrpxl0** [comment]
and if i have to download executable file from another source, then could you tell me where to download?
mod loaders that i tired don't work

**Comment by thesupersonic16** [comment]
You sent this issue report while MM is merging the project_plus branch into master, for now, grab the build from [here](https://gamebanana.com/wips/48996), later on you may need to grab it from [here](https://gamebanana.com/tools/6273) when it gets updated.

For Compiling, currently I can't compile the newest commit without removing some changes, but I'm gonna assume its just a issue on my end.
afaik you need git, WIndows SDK and Visual Studio. once you have those, clone the repo and open the sln file into Visual Studio, and you should beable to press Build and it should build.

**Comment by MainMemory** [comment]
I don't have any trouble building, but I am having issues with uploading which is delaying the release. Whichever build you have, it will detect an update when I do upload it.

**Comment by thesupersonic16** [comment]
For me I had to modify the OffsetFunctionPointer macro to get it to compile and run.

**Comment by tmvkrpxl0** [comment]
thanks for the help
