### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by mikecluck** [sonicretro/mania-mod-loader#27]
Hello! :wave:

Has there been any thought towards making this work on Linux? I understand that the UI is developed with WinForms so I know that's unlikely to change but if the rest of the code was converted from VC++ to, say, C++14 or similar, then it would be a lot easier to work with on Linux. Similarly, using .NET Core/5 instead of Framework would go a long way towards making this more universal.

My C++ skills are really rusty but I could take a look at doing this conversion unless someone more knowledgeable is already looking in to it :slightly_smiling_face:

**Comment by thesupersonic16** [comment]
Not sure about the manager, but the mod loader itself works on Linux using proton though needs to be configured to load d3d9.dll.

**Comment by mikecluck** [comment]
Interesting! Do you have any documentation or links that might help me do that? I'm not sure how to run the loader separate from the manager

**Comment by thesupersonic16** [comment]
I heard you there is some option you can change, but I never tried it, I just patched the game with a different import name and renamed the modloader with that name. I wouldn't recommend doing that.

As for the manager, I never tried it, but I don't see any reason why mono wouldn't be able to run it.

**Comment by mikecluck** [comment]
Gotcha. I'll give it a go soon and report how it goes. Thanks for your help!

**Comment by mikecluck** [comment]
I can confirm that Mono works. Thanks!

For future wayward souls:

1. [Install Mono](https://www.mono-project.com/download/stable/)
2. Follow the instructions for installing the Mania Mod Loader
3. `mono ManiaModManager.exe`
4. I have not had luck with the 1-Click Install (to be fair, I haven't tried that hard) so I have had to manually install mods by downloading and extracting them to the `mods` folder

**Comment by B-Nerd** [comment]
> I can confirm that Mono works. Thanks!
> 
> For future wayward souls:
> 
>     1. [Install Mono](https://www.mono-project.com/download/stable/)
> 
>     2. Follow the instructions for installing the Mania Mod Loader
> 
>     3. `mono ManiaModManager.exe`
> 
>     4. I have not had luck with the 1-Click Install (to be fair, I haven't tried that hard) so I have had to manually install mods by downloading and extracting them to the `mods` folder

it is better to follow the guide from the SONIC MEGAMIX MANIA discord from the mod support channel
this trick just closes the mod manager when you click save & play with a generic error code
