### ISSUE TITLE
mod loader doesn't work

### ISSUE THREAD

**Issue by randomgamer923** [sonicretro/mania-mod-loader#4]
hi,
i'm having a problem with your program.
everytime is launch the game, i get an error message saying: "The mod loader was not designed for this version of the game. Please check for the updated version of the loader. Mod functionality will be disabled."
i don't know what to do!
i'm running the latest version on windows 7 64 bit.
cheers
![error](https://user-images.githubusercontent.com/32220108/30772948-e0514eda-a066-11e7-942c-41f9c992e725.PNG)

**Comment by MainMemory** [comment]
Well it sounds like... you don't have the right version of the game. The current version of the mod loader will only work with the version of the game released on September 6th.

**Comment by randomgamer923** [comment]
oh i updated the game and it worked! thanks :D
