### ISSUE TITLE
Recent Update Broke the loader

### ISSUE THREAD

**Issue by PotterAndMatrixFan** [sonicretro/mania-mod-loader#5]
Please update the loader, as a recent Sonic Mania update broke it.

**Comment by MainMemory** [comment]
[I am fully aware of the situation](https://twitter.com/MainMemory_/status/912346218814164992). I am undecided if I will update the mod loader yet, as there is an immense amount of work required to do so.

**Comment by PotterAndMatrixFan** [comment]
Thanks for answering. I do hope you take your time to update it.

**Comment by MainMemory** [comment]
Until such time as I update the mod loader, you can [continue using the old version of the game](https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/).

**Comment by dxgldotorg** [comment]
As a heads up the release also fixes a bug with Tails in Flying Battery Zone:
https://youtu.be/EkkA6eGLuWI

**Comment by MainMemory** [comment]
I am aware of that too.

Here's an idea: why don't you try updating the mod loader to work with the latest version? Don't forget all the cheat codes.

**Comment by Araraura** [comment]
But you're the only one who can do that. And there's an entire community that are waiting for an update. You can just update it over a span of time, and I can definitely can understand why you don't really want to update it, but if the first update came a day after the release, the second after a week, and the recent one after about 3 weeks, then the next one should be somewhere between January and February. Maybe much later and maybe not at all.

**Comment by MainMemory** [comment]
That's assuming there's a pattern.

**Comment by dxgldotorg** [comment]
True, the most recent releases may be to use the PC players as guinea pigs to test the upcoming console patches, while those patches wait for manufacturer approval.
On Steam the publisher can just push an update at will, just push the bits into their upload form and watch them come out through Steam's CDN.

**Comment by Clownacy** [comment]
> But you're the only one who can do that. And there's an entire community that are waiting for an update.

Wow. Saying that on a _collaboration_ website drips with irony.

**Comment by Araraura** [comment]
Any updates soon?

**Comment by PotterAndMatrixFan** [comment]
Just do what he says and go back to the previous update. The mod loader works perfect that way.

**Comment by Araraura** [comment]
That's what I'm doing, but Codenamegamma won't release a cheat table with the new code and stuff for the older version

**Comment by MainMemory** [comment]
If you absolutely must have the latest version of the game, someone has made [a fork that works with the latest version](https://github.com/thesupersonic16/mania-mod-loader). However it does not have all of the codes ported, and neither of my mods will work with it, as they also need to be updated.

**Comment by Araraura** [comment]
We're asking this for the codes

**Comment by MainMemory** [comment]
Is there really anything in my code list that isn't also in Codenamegamma's table?

**Comment by Araraura** [comment]
It's making some little small details work in a way the table can't do.

**Comment by MainMemory** [comment]
Fixed.
